# kubernetes/staging/02-user-db.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: staging
spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-db

  template:
    metadata:
      labels:
        app: user-db

    spec:
      containers:
        - name: user-db
          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              value: users

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: user-db-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d users
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d users
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

      volumes:
        - name: user-db-storage
          persistentVolumeClaim:
            claimName: user-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: staging
spec:
  type: ClusterIP

  selector:
    app: user-db

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432