apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
        - name: student-service
          image: placeholder
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: students
            - name: POSTGRES_HOST
              value: student-db
            - name: POSTGRES_PORT
              value: "5432"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: JWT_SECRET_KEY
            - name: JWT_ALGORITHM
              value: HS256
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: AZURE_STORAGE_CONNECTION_STRING
            - name: AZURE_STORAGE_CONTAINER_NAME
              value: student-profile-photo

---
apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: staging
spec:
  selector:
    app: student-service
  ports:
    - port: 8000
      targetPort: 8000