# week08/docker-compose.yml
version: "3.8"

services:
  product_db:
    image: postgres:15-alpine
    container_name: product_db_container
    restart: always
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products"]
      interval: 5s
      timeout: 5s
      retries: 5

  order_db:
    image: postgres:15-alpine
    container_name: order_db_container
    restart: always
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 5s
      timeout: 5s
      retries: 5

  product_service:
    build:
      context: ./backend/product_service
      dockerfile: Dockerfile
    image: week08_example01_product_service:latest
    container_name: product_api_container
    restart: always
    depends_on:
      product_db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: product_db
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # For image uploads (can be dummy for local testing)
      AZURE_STORAGE_ACCOUNT_NAME: local
      AZURE_STORAGE_ACCOUNT_KEY: local
      AZURE_STORAGE_CONTAINER_NAME: product-images
      AZURE_SAS_TOKEN_EXPIRY_HOURS: "24"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/product_service/app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  order_service:
    build:
      context: ./backend/order_service
      dockerfile: Dockerfile
    image: week08_example01_order_service:latest
    container_name: order_api_container
    restart: always
    depends_on:
      order_db:
        condition: service_healthy
      product_service:
        condition: service_started
    environment:
      POSTGRES_HOST: order_db
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PRODUCT_SERVICE_URL: http://product_service:8000
    ports:
      - "8001:8000"
    volumes:
      - ./backend/order_service/app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: week08_example01_frontend:latest
    container_name: product_order_frontend
    restart: always
    depends_on:
      product_service:
        condition: service_started
      order_service:
        condition: service_started
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  product_db_data:
  order_db_data:
