apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-w08e1
  namespace: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # use your ACR image
          image: acrweek0820618.azurecr.io/frontend:latest
          ports:
            - containerPort: 80
          # read backend URLs from the ConfigMap you just made
          envFrom:
            - configMapRef:
                name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-w08e1
  namespace: shop
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
