# week08/k8s/frontend/deploy-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy           # <— matches CD workflow
  labels: { app: frontend }
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata: { labels: { app: frontend } }
    spec:
      containers:
      - name: frontend
        image: IMAGE_FRONTEND_PLACEHOLDER   # <— CD replaces this
        imagePullPolicy: Always
        ports: [{ containerPort: 80 }]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc              # <— matches CD workflow
  labels: { app: frontend }
spec:
  selector: { app: frontend }
  ports: [{ protocol: TCP, port: 80, targetPort: 80 }]
  type: LoadBalancer
