apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pvc-w08e1
  labels:
    app: order-db
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""   # remove this line to use the cluster default StorageClass

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db-deployment-w08e1
  labels:
    app: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 999          # postgres gid
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postgres
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w08e1
              key: ORDERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1
              key: POSTGRES_PASSWORD
        readinessProbe:
          exec:
            command: ["sh","-c","pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" -h 127.0.0.1"]
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
        livenessProbe:
          exec:
            command: ["sh","-c","pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" -h 127.0.0.1"]
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: order-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: order-db-data
        persistentVolumeClaim:
          claimName: order-db-pvc-w08e1

---
apiVersion: v1
kind: Service
metadata:
  name: order-db-service-w08e1
  labels:
    app: order-db
spec:
  selector:
    app: order-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
