name: CI - Build & Test

on:
  pull_request:
    branches: [ "main" ]     
  push:
    branches: [ "development" ]

env:
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Set image tag
        id: meta
        run: echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Show workspace tree (debug)
        run: |
          echo "::group::tree"
          pwd
          ls -la
          echo "---- week08/"
          ls -la week08
          echo "---- week08/backend/"
          ls -la week08/backend
          echo "---- week08/frontend/"
          ls -la week08/frontend
          echo "::endgroup::"

      - name: Build & Push product-service
        run: |
          docker build -t $REGISTRY/product-service:${{ steps.meta.outputs.TAG }} \
            -f week08/backend/product_service/Dockerfile week08/backend/product_service
          docker push $REGISTRY/product-service:${{ steps.meta.outputs.TAG }}

      - name: Build & Push order-service
        run: |
          docker build -t $REGISTRY/order-service:${{ steps.meta.outputs.TAG }} \
            -f week08/backend/order_service/Dockerfile week08/backend/order_service
          docker push $REGISTRY/order-service:${{ steps.meta.outputs.TAG }}

      - name: Build & Push frontend
        run: |
          docker build -t $REGISTRY/frontend:${{ steps.meta.outputs.TAG }} \
            -f week08/frontend/Dockerfile week08/frontend
          docker push $REGISTRY/frontend:${{ steps.meta.outputs.TAG }}

      - name: Publish deploy manifest (artifact)
        run: |
          mkdir -p out
          echo '{"tag":"'"${{ steps.meta.outputs.TAG }}"'","registry":"'"${{ env.REGISTRY }}"'"}' > out/deploy-manifest.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-manifest
          path: out/deploy-manifest.json
