# .github/workflows/deploy.yml
name: Full Deployment Pipeline (Backend + Frontend)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  backend_ci:
    uses: ./.github/workflows/backend_ci.yml
    secrets: inherit

  backend_cd:
    needs: backend_ci
    uses: ./.github/workflows/backend-cd.yml
    with:
      aks_cluster_name: week09-aks
      aks_resource_group: week09-rg
      aks_acr_name: week09acrabhi
    secrets: inherit

  frontend_ci:
    needs: backend_cd
    uses: ./.github/workflows/frontend_ci.yml
    secrets: inherit

  frontend_cd:
    needs: frontend_ci
    uses: ./.github/workflows/frontend-cd.yml
    with:
      product_api_ip: ${{ needs.backend_cd.outputs.PRODUCT_API_IP }}
      order_api_ip: ${{ needs.backend_cd.outputs.ORDER_API_IP }}
      aks_cluster_name: week09-aks
      aks_resource_group: week09-rg
    secrets: inherit
