name: Deploy Full Stack to AKS

on:
  workflow_dispatch:
    inputs:
      aks_cluster_name:
        description: "AKS Cluster"
        required: true
      aks_resource_group:
        description: "Resource Group"
        required: true
      aks_acr_name:
        description: "ACR Name"
        required: true

jobs:
  azure_login:
    runs-on: ubuntu-latest
    outputs:
      AZURE_CREDENTIALS: ${{ steps.export_creds.outputs.AZURE_CREDENTIALS }}
    steps:
      - name: Export Azure Credentials
        id: export_creds
        run: echo "::set-output name=AZURE_CREDENTIALS::${{ secrets.AZURE_CREDENTIALS }}"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  deploy_backend:
    needs: azure_login
    uses: ./.github/workflows/backend-cd.yml
    with:
      aks_cluster_name: ${{ inputs.aks_cluster_name }}
      aks_resource_group: ${{ inputs.aks_resource_group }}
      aks_acr_name: ${{ inputs.aks_acr_name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  deploy_frontend:
    needs: deploy_backend
    uses: ./.github/workflows/frontend-cd.yml
    with:
      product_api_ip: ${{ needs.deploy_backend.outputs.PRODUCT_API_IP }}
      order_api_ip: ${{ needs.deploy_backend.outputs.ORDER_API_IP }}
      aks_cluster_name: ${{ inputs.aks_cluster_name }}
      aks_resource_group: ${{ inputs.aks_resource_group }}
    secrets:
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
