# week08/.github/workflows/frontend_ci.yml
#this is to trigger frontend pipeline
name: Frontend CI - Build Frontend Image

on:
  # Manual trigger
  workflow_dispatch:

  # Automatically on pushes to development branch
  push:
    branches:
      - development
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

  # Run on pull requests targeting development or main branch
  pull_request:
    branches:
      - development
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Build Docker image only (no push)
    - name: Build Frontend Image (validation only)
      run: docker build -t frontend-ci-test ./frontend/
